send_raw_command:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: epson_test
    raw_command:
      required: true
      example: "PWR?"
      selector:
        text:

select_cmode:
  target:
    entity:
      integration: epson_test
      domain: media_player
  fields:
    cmode:
      required: true
      example: "cinema"
      selector:
        text:
